name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: |-
          Hi there!
          
          Thank you for your submission. Unfortunately, this is just a mirror of the repository. I therefore do not accept PRs on GitHub. Please review the "Contribute" section of the README, or visit this project [at sourcehut](https://git.sr.ht/~poldi1405/glog) to contribute. (You can just send this PR via email. No account needed.)
